### PR TITLE
Add metric endpoint

### PR DESCRIPTION
**Pull request by msiuts**
This adds a prometheus metrics endpoint which exposes some metrics like error counters and reconcile counters.

This fixes https://github.com/FairwindsOps/rbac-manager/issues/70.

### CODE REVIEW

**Comment by sudermanjr** [comment]
This approach looks solid.  Looking forward to a more complete PR.

I was going to try and review this more, but it seems to panic on me when I run it as-is right now.

Thanks for all the work so far!!!!

**Comment by msiuts** [comment]
Thank you for the feedback. Now it is working.

**Comment by msiuts** [comment]
@sudermanjr I temporally published a docker image for easier testing here: 
https://hub.docker.com/r/coderaid/rbac-manager

So far it works fine. I guess I will add some tests and then would like to discuss which additional metrics are needed.

**Comment by sudermanjr** [comment]
Hoping to take a look at this today or early next week. Thanks!

**Pull request merged**
