### PR TITLE
Add kustomization.yml

### PR DESCRIPTION
**Pull request by sim1**
This allows the use of rbac-manager as a remote base for kustomize.

### CODE REVIEW

**Review by sudermanjr — CHANGES_REQUESTED** [review]
I think that either this file needs to live in the `deploy` directory, or that the paths need to be in the kustomization file. Currently if I try to kustomize build I get errors.

**Comment by sim1** [comment]
You're right, my bad, I've added the deploy as path of the resource files

```
kustomize build 'https://github.com/sim1/rbac-manager?ref=patch-1' | grep '^kind'
kind: Namespace
kind: CustomResourceDefinition
kind: ServiceAccount
kind: ClusterRole
kind: ClusterRoleBinding
kind: Deployment
```

**Review by sudermanjr — APPROVED** [review]
Thanks

**Comment by sim1** [comment]
😪

**Pull request closed without merging**
